server:
  port: 10000
spring:
  application:
    name: api-gateway
zuul:
  ignoredServices: "*"
  routes:
    one:
     path: /one/**
     serviceId: one
     stripPrefix: false
    two:
     path: /two/**
     serviceId: two
     stripPrefix: false
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://servicediscovery:8761/eureka}
management:
  security.enabled: false