server:
  port: 8888
  servlet:
   context-path: /config
spring:
  application:
    name: configserver
  cloud:
      config:
        server:
          git:
            uri: https://github.com/amardeepkhera/springcloudstack
            basedir: target/configurations
            searchPaths: configurations
            clone-on-start: true
logging:
  level:
   org.springframework.*: DEBUG

