server:
  port: 8888
  servlet:
   context-path: /config
spring:
  application:
    name: configserver
  cloud:
      config:
        server:
          git:
            uri: https://github.com/amardeepkhera/springcloudstack
            basedir: target/configurations
            searchPaths: configurations
            clone-on-start: true
        label: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://servicediscovery:8761/eureka}
    healthcheck:
     enabled: true
  instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
logging:
  level:
   org.springframework.*: INFO

