eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://servicediscovery:8761/eureka}
    healthcheck:
          enabled: true
  instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
cloud:
 config:
  label: config-server
#   uri: http://localhost:8888/config
 discovery:
  service-id: configserver
  enabled: true