eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://servicediscovery:8761/eureka}
    healthcheck:
          enabled: true
  instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
cloud:
 discovery:
  service-id: configserver
  enabled: true
logging:
 level:
  org.springframework.*: DEBUG