server:
  port: 8761
spring:
 cloud:
  config:
   label: config-server
eureka:
  instance:
    hostname: servicediscovery
    leaseRenewalIntervalInSeconds: 2
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
