server:
  port: 8762
spring:
  application:
    name: Two
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://servicediscoveryserver:8761/eureka}
    healthcheck:
          enabled: true
  instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
